### ISSUE TITLE
ValueError: Attempting to unscale FP16 gradients.

### ISSUE THREAD

**Issue by QQQ300kuai** [FunAudioLLM/InspireMusic#40]
Thanks for the greate work.  When I was training the LLM model with the run.sh, I meet the following problem. The LLM model  was training with FP16,

/data/InspireMusic/inspiremusic/utils/train_utils.py", line 252, in update_parameter_and_lr
      scaler.unscale_(optimizer)  # Unscale gradients before clipping
    File "/data/InspireMusic/anaconda3/envs/inspiremusic/lib/python3.8/site-packages/torch/amp/grad_scaler.py", line 337, in unscale_
      optimizer_state["found_inf_per_device"] = self._unscale_grads_(
    File "/data/InspireMusic/anaconda3/envs/inspiremusic/lib/python3.8/site-packages/torch/amp/grad_scaler.py", line 259, in _unscale_grads_
      raise ValueError("Attempting to unscale FP16 gradients.")
  ValueError: Attempting to unscale FP16 gradients.

**Comment by iris2c** [comment]
Thank you for your comments. However, we cannot reproduce this error.

**Comment by dongwon00kim** [comment]
I also got same error.

I changed antlr4-python3-runtime version to 4.9.3 in requirement.txt file due to dependency issue with hydra-core version 1.3.2.

@iris2c could you share Dockerfile or docker image?

**Comment by dongwon00kim** [comment]
This issue appears to be identical to issue https://github.com/FunAudioLLM/InspireMusic/issues/18.

**Comment by dongwon00kim** [comment]
Dear @iris2c, @QQQ300kuai 

I modified https://github.com/FunAudioLLM/InspireMusic/blob/main/examples/music_generation/conf/inspiremusic_base.yaml file as below.

I changed the dtype of qwen encoder(llm) to fp32. Please check if this is correct.


```
llm: !new:inspiremusic.llm.llm.LLM
    text_encoder_input_size: !ref <text_encoder_input_size>
    llm_input_size: !ref <llm_input_size>
    llm_output_size: !ref <llm_output_size>
    audio_token_size: 4096
    length_normalized_loss: True
    lsm_weight: 0
    text_encoder_conf:
        name: "none"
    llm: !new:inspiremusic.transformer.qwen_encoder.QwenEmbeddingEncoder
        input_size: !ref <text_encoder_input_size>
        pretrain_path: !ref <basemodel_path>
        dtype: "fp32"
```
